added models
wyncode/C40_resiliency pull request #10
Opened 2020-12-16 02:30 UTC by jessicapalomo

Closes #9.

2020-12-17 13:29 UTC, leopolicastro requested changes

2020-12-17 13:29 UTC, leopolicastro commented on server/db/models/requests.js
> +const Request = mongoose.model('Request', userSchema);
Is it a `userSchema` or `requestSchema`

2020-12-17 13:29 UTC, leopolicastro commented on server/db/models/requests.js
> +    type: Image,
I don't believe there is an Image data type.  This should be saved as a `String`

2020-12-17 13:29 UTC, leopolicastro commented on server/db/models/users.js
> +      required: true
I would use the `Date` data type for this one. Makes it easier to work with dates.

2020-12-18 02:34 UTC, jessicapalomo commented on server/db/models/requests.js
> +    type: Image,
Thanks, was wondering

2020-12-18 13:47 UTC, leopolicastro approved these changes

2020-12-18 13:47 UTC, leopolicastro commented on package.json
> +    "set-cookie-parser": "^2.4.6",
Which package is set cookie parser?

2020-12-18 13:59 UTC, leopolicastro approved these changes

2020-12-18 14:01 UTC, merged